### PR TITLE
Add ability to set acronym "title" inside data-attribute

### PR DESCRIPTION
**Pull request by dosandk**
To set custom styling for native "title" attribute, unfortunately, impossible. So, was added the ability to set acronym description inside the "data-title" attribute, which can be easily styled with CSS.

### CODE REVIEW

**Comment by PedroLamas** [comment]
Hi @dosandk, thank you for this.

However, this can be very easily achieved with MDX components!

Here's an example for what you requested:

```javascript
// src/App.js
import React from 'react';
import { MDXProvider } from '@mdx-js/react';

const Acronym = ({title, ...props}) => <abbr data-title={title} {...props} />;

const components = {
  abbr: Acronym,
};

export default props => (
  <MDXProvider components={components}>
    <main {...props} />
  </MDXProvider>
);
```

**Comment by dosandk** [comment]
Hi @PedroLamas, thanks for replay!

yes, of course, it can be solved with MDX components, 
but if a project doesn't use MDX for some reason:
* it already has a lot "*.md" files and changes to MDX will take a lot of efforts 
* developers want to keep markdown files as much purer (it allows to reuse markdown files in some other sources)

I thought that it will be helpful to use additional param like "data-title" attribute to make styling for tooltip more flexible and allows users to decide which format "md" or "mdx" to use.

**Comment by PedroLamas** [comment]
There seems to be a misconception here, as there is no need to change the *.md files to add MDX support - I say this by personal experience, as I just write pure markdown and didn't change anything in mine (the markdown content is the same as I was using under Jekyll) as you can see here: https://github.com/PedroLamas/pedrolamas.com/tree/master/content

**Comment by PedroLamas** [comment]
Closing this for now as I don't see a specific scenario where this would be valuable - unless you are not using MDX, and in that case there are other solutions that don't require this kind of change on the plugin.

**Pull request closed without merging**
